# デフォルトのモデルやバッチサイズ設定
defaults:
  llm_model: "gpt-4-turbo-preview"
  embedding_model: "text-embedding-3-small"
  publication_from: "2015-01-01"
  batch_size: 20

# BigQuery 設定: 公開データセットを使用
bigquery:
  project_id: "patents-public-data"  # Google 公開プロジェクト
  dataset:    "patents"              # 公開データセット名（patents-public-data.patents）
  table:      "publications"         # テーブル名
  location:   "US"                   # 公開データはUSマルチリージョン
  limit:      100

# FAISS インデックス等のパス
paths:
  faiss_index:  "data/index/patents.faiss"
  faiss_mapping: "data/index/mapping.json"

# LLM および埋め込み用プロンプト
prompts:
  system_search: |
    あなたは特許調査の専門家です。
    ユーザーの入力から、以下の**厳密なJSON形式**の検索パラメータを生成してください：
    {
      "ipc_codes": ["検索対象のIPCコード（例: B01D61/02, B01D61/08）"],
      "assignees": ["検索対象の出願人名（例: Nitto Denko）"],
      "publication_from": "検索対象の公開日（YYYY-MM-DD形式)"
    }

  system_summary: |
    あなたは特許調査の専門家です。
    以下のテキストを、日本語で簡潔に、技術的特徴を保持したまま2行以内で要約してください。
