# デフォルトのモデルやバッチサイズ設定
defaults:
  llm_model: "gpt-4-turbo-preview"
  embedding_model: "text-embedding-3-small"
  publication_from: "2015-01-01"
  batch_size: 20

# BigQuery 設定: 実行プロジェクトと参照する公開データセットを分離
bigquery:
  project_id: "corded-guild-459506-i6"      # ジョブ実行と請求に使う自分のプロジェクトID
  public_project_id: "patents-public-data"  # クエリ対象となる公開データセットのプロジェクトID
  dataset:          "patents"               # 公開データセット名
  table:            "publications"          # テーブル名
  location:         "US"                    # データセットのロケーション
  limit:            100

# FAISS インデックス等のパス
paths:
  faiss_index:  "data/index/patents.faiss"
  faiss_mapping: "data/index/mapping.json"

# LLM および埋め込み用プロンプト
prompts:
  system_search: |
    あなたは特許調査の専門家です。
    ユーザーの入力から、以下の**厳密な JSON**形式の検索パラメータを生成してください。
    絶対に余計な説明文を含まず、**純粋な JSON オブジェクト**だけを返してください：
    {
      "ipc_codes": ["B01D61/02", "B01D61/08", "C02F1/44"],
      "assignees": [],
      "publication_from": "YYYY-MM-DD"
    }

  system_summary: |
    あなたは特許調査の専門家です。
    以下のテキストを、日本語で簡潔に、技術的特徴を保持したまま2行以内で要約してください。
    レスポンスに余計な引用符やマークダウンを含めないでください。


chat_flow:
  initial_prompt: |
    こんにちは！🚀 どんな特許情報をお探しですか？
    気になる技術や公開日、調査したい国やキーワードなど、思いつくまま教えてください♪
  proposal_prompt: |
    以下のユーザー回答をもとに、特許調査の検索パラメータを**厳密なJSON形式**で提案してください。
    keys:
      - ipc_codes: リスト形式で複数のIPCコードを指定（例：B01D, C02F）
      - publication_from: YYYY-MM-DD形式で公開日下限を指定
      - countries: 対象国コードのリスト（例：JP, US, EP）
      - keywords: 検索に含めたいキーワードのリスト
