defaults:
  llm_model: "gpt-4-turbo-preview"
  embedding_model: "text-embedding-3-small"
  publication_from: "2015-01-01"
  max_results: 5
  batch_size: 20

bigquery:
  project_id: "corded-guild-459506-i6"
  dataset: "patents"
  table: "publications"
  limit: 100

paths:
  faiss_index: "data/index/patents.faiss"
  faiss_mapping: "data/index/mapping.json"
  raw_data: "data/raw/patents.csv"

prompts:
  system_search: |
    あなたは特許調査の専門家です。
    ユーザーの入力から、以下のJSON形式で検索パラメータを生成してください：
    {
      "ipc_codes": ["検索対象のIPCコード（複数可）"],
      "assignees": ["検索対象の出願人名（複数可）"],
      "publication_from": "検索対象の公開日（YYYY-MM-DD形式）"
    }
    
    ※条件が特定できない場合は空の配列または省略可能です。

  system_summary: |
    あなたは特許調査の専門家です。
    以下の要約を、技術的な特徴を保ちながら、日本語で簡潔に要約してください。
    長さは2行以内としてください。