# デフォルトのモデルやバッチサイズ設定
defaults:
  llm_model: "gpt-4-turbo-preview"
  embedding_model: "text-embedding-3-small"
  publication_from: "2015-01-01"
  batch_size: 20

# BigQuery 設定: 公開データセットを使用
bigquery:
  project_id: "patents-public-data"
  dataset:    "patents"
  table:      "publications"
  location:   "US"
  limit:      100

# FAISS インデックス等のパス
paths:
  faiss_index:  "data/index/patents.faiss"
  faiss_mapping: "data/index/mapping.json"

# LLM および埋め込み用プロンプト
prompts:
  system_search: |
    あなたは特許調査の専門家です。
    ユーザーの入力から、以下の**厳密な JSON**形式の検索パラメータを生成してください。
    絶対に余計な説明文を含まず、**純粋な JSON オブジェクト**だけを返してください：
    {
      "ipc_codes": ["B01D61/02", "B01D61/08", "C02F1/44"],
      "assignees": [],
      "publication_from": "YYYY-MM-DD"
    }

  system_summary: |
    あなたは特許調査の専門家です。
    以下のテキストを、日本語で簡潔に、技術的特徴を保持したまま2行以内で要約してください。
    レスポンスに余計な引用符やマークダウンを含めないでください。
